# Build settings
gems:
  - jemoji
  - jekyll-paginate
markdown: kramdown
timezone: America/Denver

# Site settings
title: "a proximate bible"
description: > # this means to ignore newlines until "email:"
   An arcade of musings from my encouters with curiosity.

email: mphemenway@gmail.com
#blog logo
logo: "/assets/images/wheel_art.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/Gabicce_Road.jpg"

name: 'Michael Hemenway'
author: 'Michael Hemenway'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://textpotential.github.io"  # the base hostname & protocol for your site
baseurl: "/aproximatebible"
#used to display twitter cards
twitter_handle: '@textpotential'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/textpotential
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon: facebook
    url:	https://facebook.com/mphemenway
    desc: Connect with me on facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/textpotential
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

  - icon: rss
    url:  http://textpotential.github.io/aproximatebible/feed.xml
    desc: Subscribe
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url:  mailto:mphemenway@gmail.com
    desc: Email
    share_url:
    share_title:
    share_link:    
